# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  majorVersion: '1'
  minorVersion: '0'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'build'
- script: dotnet test test/UnitTest/UnitTest.csproj --configuration $(buildConfiguration) --logger trx
  displayName: 'unit test'  
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'publish test results'
- script: dotnet pack src/Ermine/Ermine.csproj --configuration $(buildConfiguration) --no-build /p:Version=$(majorVersion).$(minorVersion).$(Build.BuildId)
  displayName: 'create package'
- task: DotNetCoreCLI@2
  inputs:
    command: push
    nuGetFeedType: internal
    publishVstsFeed: ermine
    packagesToPush: '**/*nupkg'
  displayName: 'pubish package'